# Generated by Django 5.2.7 on 2025-10-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendedor', '0002_alter_vendedor_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='rg',
            field=models.IntegerField(),
        ),
    ]
