# Generated by Django 5.2.7 on 2025-10-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendedor', '0003_alter_vendedor_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='data_nascimento',
            field=models.DateTimeField(),
        ),
    ]
