# Generated by Django 5.2.7 on 2025-10-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendedor', '0004_alter_vendedor_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='rg',
            field=models.CharField(max_length=20),
        ),
    ]
